### ISSUE TITLE
Compile error: too many arguments to function 'VWF_RenderSingle'

### ISSUE THREAD

**Issue by planet36** [snesrev/zelda3#274]
### Describe your bug here. And how to reproduce it.

Trying to compile in a Linux environment with gcc 13.2.1, I get the following error:

```src/messaging.c: In function ‘RenderText_Draw_MessageCharacters’:
src/messaging.c:2394:5: error: too many arguments to function ‘VWF_RenderSingle’
 2394 |     VWF_RenderSingle(TEXTCMD_PARAM(cmd));
      |     ^~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

There's a conflict in the function signature of `VWF_RenderSingle`.

### What is your build target?

Linux

**Comment by impeeza** [comment]
Sorry buddy, just build on Ubuntu without problem:

![image](https://github.com/snesrev/zelda3/assets/41979604/2957d8c7-a5ad-48af-b199-cbf85565ccd0)

following the instructions on:

https://github.com/snesrev/zelda3#installing-libraries-on-linuxmacos

**Comment by planet36** [comment]
I had `-std=` set to `c2x` when the build failed.  When it's `c17` or older, it builds fine.

**Comment by Traace** [comment]
Hi,
I'm running MacOS Sonoma 14.1 on Apple Silicion.

I just tried to build this project based on the instructions: https://github.com/snesrev/zelda3#installing-libraries-on-linuxmacos

But it failes for the same reson. The code isn't compatible with C2x. I tried to set -std=c17 via CFLAGS. But the build still failes.

Please provide updated instructions that can produce a working build.
